plugins {
    id 'java'
}

group = 'com.browserstack'
version = '1.0'
description = 'browserstack-demo-testng'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.appium:java-client:8.6.0'
    implementation 'org.seleniumhq.selenium:selenium-java:4.13.0'
    implementation 'org.testng:testng:7.9.0'
    implementation 'com.browserstack:browserstack-java-sdk:1.41.0'
    implementation 'io.rest-assured:rest-assured:4.3.3'
}

def browserstackSDKArtifact = configurations.compileClasspath.resolvedConfiguration.resolvedArtifacts.find { it.name == 'browserstack-java-sdk' }

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(Test) {
    systemProperties = System.properties
    dependsOn compileTestJava
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    outputs.upToDateWhen { false }
    useTestNG() {
        useDefaultListeners = true
    }
    jvmArgs "-javaagent:${browserstackSDKArtifact.file}"
}

test {
    systemProperty 'browserstack.config', 'src/test/resources/web/config/web_single.yml'
    include '**/desktop/SingleTest.class'
}

task webSingle(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/web/config/web_single.yml'
    filter {
        includeTestsMatching 'com.test.web.desktop.SingleTest'
    }
}

task webParallel(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/web/config/web_parallel.yml'
    filter {
        includeTestsMatching 'com.test.web.desktop.SingleTest'
    }
}

task webLocal(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/web/config/web_local.yml'
    filter {
        includeTestsMatching 'com.test.web.desktop.LocalTest'
    }
}

task webFail(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/web/config/web_single.yml'
    filter {
        includeTestsMatching 'com.test.web.desktop.FailTest'
    }
}

task androidSingle(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/android_single.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.android.SingleTest'
    }
}

task androidParallel(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/android_parallel.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.android.SingleTest'
    }
}

task androidLocal(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/android_local.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.android.LocalTest'
    }
}

task androidFail(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/android_single.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.android.FailTest'
    }
}

task iosSingle(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/ios_single.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.ios.SingleTest'
    }
}

task iosParallel(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/ios_parallel.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.ios.SingleTest'
    }
}

task iosLocal(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/ios_local.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.ios.LocalTest'
    }
}

task iosFail(type: Test) {
    systemProperty 'browserstack.config', 'src/test/resources/app/config/ios_single.yml'
    filter {
        includeTestsMatching 'com.test.app.appium.ios.FailTest'
    }
}

task espresso(type: Test) {
    jvmArgs = []
    filter {
        includeTestsMatching 'com.test.app.espresso.EspressoTest'
    }
}

task xcuitest(type: Test) {
    jvmArgs = []
    filter {
        includeTestsMatching 'com.test.app.xcui.XCUITest'
    }
}

task runServer(type: JavaExec) {
    group = 'application'
    description = 'Run the HTTP server'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.local.server.MyHttpServer'
}
